# Generated by Django 2.0.5 on 2018-05-26 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180526_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 26, 18, 51, 18, 842718)),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
