# Generated by Django 2.0.5 on 2018-06-01 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20180526_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 19, 37, 42, 493263)),
        ),
    ]
