# Generated by Django 2.0.5 on 2018-06-01 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_auto_20180601_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 19, 53, 32, 925854)),
        ),
    ]
