# Generated by Django 2.0.5 on 2018-05-25 11:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 5, 25, 16, 33, 30, 916032))),
                ('start_date', models.DateTimeField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('completed_date', models.DateTimeField(blank=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.Status')),
            ],
        ),
    ]
